
# Site settings
title: "Jaron Ellingson"
author: "Jaron Ellingson"
description: "Ph.D. Robotics Engineer | Control • Estimation • Autonomous Systems • Reinforcement Learning • Computer Vision • SLAM"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaringson.github.io" # the base hostname & protocol for your site

# Social links
github_username: jaringson
linkedin_username: jaron-ellingson

# Build settings
theme: minima
markdown: kramdown
